version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hacker678876
      MYSQL_DATABASE: expobaku
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: hacker678876
    depends_on:
      - db

  server:
    container_name: nestjs_server
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=hacker678876
      - DATABASE_NAME=expobaku
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: yarn start:dev
    restart: on-failure

volumes:
  db-data:
